routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Auth::routes();

Route::get('/', 'HouseController@index')->name('houseList');
Route::get('editHouse', 'HouseController@editIndex')->name('editHouse');

Route::resource('house', 'HouseController');
Route::get('houseCreate', 'HouseController@create')->name('houseCreate')->middleware('auth');
Route::post('addHouse', 'HouseController@store')->middleware('auth');
Route::post('searchHouse', 'HouseController@search')->name('searchHouse');
Route::post('consumeXML', 'HouseController@consumeXML')->middleware('auth');


Route::get('/viewXML', function(){
	return view('house.xml');
})->middleware('auth');

app/House.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class House extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'type', 'user_id',
    ];
}

app/Http/Controllers/HouseController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use illuminate\pagination;
use Illuminate\Support\Facades\Input;
use Auth;
use App\House;

use App\Http\Controllers\HouseDescController as House_Desc;
use App\Http\Controllers\AddressController as House_Address;
use App\Http\Controllers\ImageController as House_Image;

class HouseController extends Controller
{

    public function __construct(){

        $this->HouseDesc = new House_Desc();
        $this->Address = new House_Address();
        $this->Image = new House_Image();

    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $houses = House::leftJoin('house_descs', 'houses.id', '=', 'house_descs.house_id')
            ->select('houses.*', 'house_descs.*')
            ->paginate(6);
        return view('house.view')->with(compact('houses'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function editIndex()
    {
        $user = Auth::user();
        $houses = House::where('user_id', '=', $user->id )
            ->paginate(6);
        return view('house.editList')->with(compact('houses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('house.create');
    }

    public function validateRequest(Request $request)
    {
        $this->validate($request, array(                
            'title' => 'required',
            'type' => 'required'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = Auth::user();
        $this->validateRequest($request);

        // create House        
        $house = House::create([
            'title' => $request->title,
            'type' => $request->type,
            'user_id' => $user->id
        ]);

        $house = $house->fresh();

        $this->HouseDesc->store($request, $house->id);        
        $this->Address->store($request, $house->id);        
        
        if(sizeof($request->files) > 0){
            var_dump('first working');
            $this->Image->upload($request, $house->id);            
        }

        // redirect to the list page

         return redirect()->route('houseList');
    }

    private function formatDataSet($imovel)
    {
        $result = [];
        $photos = [];

        $result['title'] = (string)$imovel->TipoImovel;
        $result['type'] = (string)$imovel->SubTipoImovel;
        $result['cep'] = (string)$imovel->CEP;
        $result['city'] = (string)$imovel->Cidade;
        $result['state'] = (string)$imovel->UF;
        $result['block'] = (string)$imovel->Bairro;
        $result['number'] = (int)$imovel->Numero;
        $result['complement'] = (string)$imovel->Complemento;
        $result['value'] = ((float)$imovel->PrecoVenda !== '') ? (float)$imovel->PrecoVenda  : ((float)$imovel->PrecoLocacao !== '')? (float)$imovel->PrecoLocacao : (float)$imovel->PrecoLocacaoTemporada ;
        $area = ((float)$imovel->AreaTotal > 0) ? (float)$imovel->AreaTotal : 1;
        $result['sqrtValue'] = ($result['value']/sqrt($area));
        $result['type'] = 'Casa';
        $result['qttyBed'] = (int)$imovel->QtdDormitorios + (int)$imovel->QtdSuites;;
        $result['qttyBath'] = (int)$imovel->QtdBanheiros;
        $result['qttyLiving'] = (int)$imovel->QtdSalas;
        $result['garage'] = (int)$imovel->QtdVagas;
        $result['description'] = (string)$imovel->Observacao;
        
        foreach ($imovel->Fotos as $foto) {            
            array_push($photos, $foto);
        }
        $result['photos'] = $photos;
        return $result;
    }

    private function storeXML($result)
    {
        $user = Auth::user(); 
         
        $house = House::create([
            'title' => (string)$result['title'],
            'type' => (string)$result['type'],
            'user_id' => $user->id
        ]);

        $house = $house->fresh();

        $this->HouseDesc->storeXML($result, $house->id);
        $this->Address->storeXML($result, $house->id);
        $this->Image->uploadXML($result, $house->id);        
    }

    public function consumeXML(Request $request)
    {        
        $file = $request->file('xmlFile');                
        
        if($file){

            $content = utf8_encode(file_get_contents($file));
            $xml = simplexml_load_string($content);            

            foreach ($xml->Imoveis->Imovel as $value) {                
                $result = $this->formatDataSet($value);                
                $this->storeXML($result);
            }
        }

        return view('home');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {        
        $house = House::find($id);
        $houseDesc = $this->HouseDesc->find($id);
        $address = $this->Address->find($id);
        $images = $this->Image->find($id);

        return view('house.show')->with(compact('house'))->with(compact('houseDesc'))->with(compact('address'))->with(compact('images'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $house = House::find($id);
        $desc = $this->HouseDesc->find($house->id);
        $address = $this->Address->find($house->id);
        
        return view('house.edit')
            ->with(compact('house'))
            ->with(compact('desc'))
            ->with(compact('address'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $house = House::findOrFail($id);
        $user = Auth::user();

        if($house->user_id == $user->id){
            $house->title = $request->title;
            $house->type = $request->type;
            $house->save();

            $this->HouseDesc->update($request, $id);
            $this->Address->update($request, $id);
        }else{
            return view('house.view');
        }

        return view('house.edit');
    }

    public function search(){
        $searchedId = Input::post('search');
        
        $house = House::find($searchedId);

        if($house){
            return redirect()->route('house.show', $house->id);
        }else{
            return redirect()->route('houseList');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        House::destroy($id);

        return redirect()->route('editHouse');
    }
}

resources/views/house/create.blade.php
@extends('layouts.app')    

@section('content')

    <script>
        $(document).ready(function(){
            $("form").keypress(function(e) {
              //Enter key
              if (e.which == 13) {
                return false;
              }
            });

            $('#fetchCEP').on('click', function(event){
                    event.preventDefault();
                    var cep = document.getElementById('cepNumber').value;
                    cep = cep.replace(/\D/g,'');

                    if(cep.length == 8){                        
                        $.ajax({
                            url: 'https://viacep.com.br/ws/'+cep+'/json',
                            method:"POST",
                            success:function(data)
                            {
                                document.getElementById('city').value = data.localidade;
                                document.getElementById('state').value = data.uf;
                                document.getElementById('complement').value = data.logradouro;
                                document.getElementById('block').value = data.bairro;
                            }
                        });
                    }
            });
        });
    </script>

    <div class="container">     
        <form action="/addHouse" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="row d-flex" style="justify-content: space-around;">            
                <div class="form-group house-form-body">
                    <input class="form-control" type="text" name="title" placeholder="title">
                    <input class="form-control" type="text" name="type" placeholder="type">
                    <input class="form-control" type="text" name="value" placeholder="value">
                    <input class="form-control" type="text" name="sqrtValue" placeholder="sqrtValue">
                </div>
                <div class="form-group house-form-body">
                    <input class="form-control" type="text" name="type" placeholder="type">
                    <input class="form-control" type="text" name="qttyBed" placeholder="qttyBed">
                    <input class="form-control" type="text" name="qttyBath" placeholder="qttyBath">
                    <input class="form-control" type="text" name="qttyLiving" placeholder="qttyLiving">
                    <input class="form-control" type="text" name="garage" placeholder="garage">
                </div>
                <div class="form-group house-form-body">
                    <label><strong>Description: </strong></label> <br>
                    <textarea rows="5" cols="50" class="form-control" type="text" name="description" placeholder="description"></textarea>
                </div>
            </div>
            <div class="row d-flex" style="justify-content: space-around;">
                <div class="form-group house-form-body">
                    <div id="fetchCEP" class="d-flex" style="flex-direction: row; justify-content: space-around;">
                        <input id="cepNumber" class="form-control" type="text" name="cep" placeholder="cep">                        
                        <button id="fetchCEP" type="button" class="btn"> Fetch CEP </button>
                    </div>
                    <input id='city' class="form-control" type="text" name="city" placeholder="city">
                    <input id='state' class="form-control" type="text" name="state" placeholder="state">
                    <input id='block' class="form-control" type="text" name="block" placeholder="block">
                    <input class="form-control" type="text" name="number" placeholder="number">
                </div>
                <div class="form-group house-form-body">
                    <label><strong>Complemento: </strong></label> <br>
                    <textarea id="complement" rows="5" cols="50" class="form-control" type="text" name="complement" placeholder="complement"></textarea>
                </div>                
            </div>
            <div class="d-flex row form-group" style="justify-content: center;">
                <div class="d-flex" style="flex-direction: column; justify-content: center">
                    <input class="form-control" type="file" id="gallery" name="files[]" multiple />
                    <button type="submit" class="btn btn-success" style="margin-top: 10px;" > Salvar </button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/house/edit.blade.php
@extends('layouts.app')    

@section('content')
      <div class="container">
            <form action="/house/{{$house->id}}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('PATCH') }}
                  <div class="col d-flex" style="flex-direction: column;">
                        <div class="row house-box">
                              <label>Title </label>
                              <input name="title" value="{{ $house->title }}"/>
                              <label>Type</label>
                              <input name="type" value="{{ $house->type }}"/>
                              <label>Value</label>
                              <input name="value" value="{{ $desc[0]->value }}" />
                              <label>SqrtValue</label>
                              <input name="sqrtValue" value="{{ $desc[0]->sqrtValue }}" />
                        </div>
                        <div class="row house-box">
                              <label>Type</label>
                              <input name="type" value="{{ $desc[0]->type }}"/>
                              <label>QttyBed</label>
                              <input name="qttyBed" value="{{ $desc[0]->qttyBed }}"/>
                              <label>QttyBath</label>
                              <input name="qttyBath" value="{{ $desc[0]->qttyBath }}">
                              <label>QttyLiving</label>
                              <input name="qttyLiving" value="{{ $desc[0]->qttyLiving }}"/>
                              <label>Garage</label>
                              <input name="garage" value="{{ $desc[0]->garage }}" />
                        </div>
                        <div class="row house-box">
                              <label>Description</label><br>
                              <textarea rows="5" cols="50" class="form-control" type="text" name="description"> {{ $desc[0]->description }} </textarea>
                        </div>
                        <div class="row house-box">
                              <label>Cep</label>
                              <input name="cep" value="{{ $address[0]->cep }}"/>
                              <label>City</label>
                              <input name="city" value="{{ $address[0]->city }}"/>
                              <label>State</label>
                              <input name="state" value="{{ $address[0]->state }}" />
                        </div>
                        <div class="row house-box">
                              <label>Block</label>
                              <input name="block" value="{{ $address[0]->block }}"/>
                              <label>Number</label>
                              <input name="number" value="{{ $address[0]->number }}"/>
                        </div>
                        <div class="row house-box">                        
                              <label>Complement</label><br>
                              <textarea rows="5" cols="50" class="form-control" type="text" name="complement" > {{ $address[0]->complement }} </textarea>
                        </div>
                        <div class="row house-box">
                              <button type="submit" class="btn btn-success" style="margin-top: 10px;" > Salvar </button>
                        </div>
                  </div>    
            </form>        
      </div>
      <script>
            
      </script>
@endsection

resources/views/house/editList.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @foreach($houses as $house)
            
            <div class="card house-card d-flex">
                <div class="card-block d-flex" style=" flex-direction: column; text-align: center">
                    <label> ID: {{ $house->id }} </label>
                    <label> Titulo: {{ $house->title }} </label>
                </div>
                <div class="card-block d-flex" style="justify-content: space-around;">
                    <a href="{{ route('house.edit', $house->id)}}" class="btn btn-warning" style="margin-top: 20px;margin-bottom: 20px"> Edit </a>                    
                    <form method="POST" action="{{ route('house.destroy', $house->id)}}">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}

                        <input type="submit" class="btn btn-danger" style="margin-top: 20px;margin-bottom: 20px" value="Delete">
                    </form>
                </div>
            </div>

            @endforeach
        </div>
    </div>
    <div class="d-flex" style="margin-top: 20px; justify-content: center;">
        <?php echo $houses->render(); ?>
    </div>
@endsection

resources/views/house/show.blade.php
@extends('layouts.app')    

@section('content')    
      <div class="container">
            <div class="col d-flex" style="flex-direction: column;">
                  <div class="row house-box">
                        <label name="title"> <strong>Title:</strong> {{ $house->title }} </label>
                        <label name="type"> <strong>Type:</strong> {{ $house->type }} </label>
                        <label name="value"> <strong>Value:</strong> {{ $houseDesc[0]->value }} </label>
                        <label name="sqrtValue"> <strong>SqrtValue:</strong> {{ $houseDesc[0]->sqrtValue }} </label>
                  </div>
                  <div class="row house-box">
                        <label name="type"> <strong>Type:</strong> {{ $houseDesc[0]->type }} </label>
                        <label name="qttyBed"> <strong>QttyBed:</strong> {{ $houseDesc[0]->qttyBed }} </label>
                        <label name="qttyBath"> <strong>QttyBath:</strong> {{ $houseDesc[0]->qttyBath }} </label>
                        <label name="qttyLiving"> <strong>QttyLiving:</strong> {{ $houseDesc[0]->qttyLiving }} </label>
                        <label name="garage"> <strong>Garage:</strong> {{ $houseDesc[0]->garage }} </label>
                  </div>
                  <div class="row house-box">                        
                        <strong>Description:</strong> <br>
                        <label name="description"> {{ $houseDesc[0]->description }} </label>
                  </div>
                  <div class="row house-box">
                        <label name="cep"> <strong>Cep:</strong> {{ $address[0]->cep }} </label>
                        <label name="city"> <strong>City:</strong> {{ $address[0]->city }} </label>
                        <label name="state"> <strong>State:</strong> {{ $address[0]->state }} </label>
                  </div>
                  <div class="row house-box">
                        <label name="block"> <strong>Block:</strong> {{ $address[0]->block }} </label>
                        <label name="number"> <strong>Number:</strong> {{ $address[0]->number }} </label>
                  </div>
                  <div class="row house-box">
                        <strong>Complement:</strong> <br>
                        <label name="complement"> {{ $address[0]->complement }} </label>
                  </div>
            </div>
            <div id="slide" class="carousel slide" data-ride="carousel">
                  <div class="carousel-inner">
                        @foreach($images as $key => $image)
                              @if($key == 0)
                                    <div class="carousel-item active">
                                          <img class="d-block w-100" src="{{$image->url}}" alt="{{$image->name}}">
                                    </div>
                              @else
                                    <div class="carousel-item">
                                          <img class="d-block w-100" src="{{$image->url}}" alt="{{$image->name}}">
                                    </div>
                              @endif
                        @endforeach
                  </div>
                  <a class="carousel-control-prev" href="#slide" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" style="background-color: black" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                  </a>
                  <a class="carousel-control-next" href="#slide" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" style="background-color: black" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                  </a>
            </div>
      </div>
@endsection

resources/views/house/view.blade.php
@extends('layouts.app')
    
<?php
    use illuminate\pagination;
?>

@section('content')    
    <div class="container">
        <div class="d-flex" style="flex-direction: column;">
            <div class="d-flex" style="flex-direction: row; justify-content: center;margin-bottom: 20px">
                <form class="d-flex" action="/searchHouse" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <input id="search" class="form-control" type="text" name="search">
                    <button id="findHouse" type="submit" class="btn-primary" style="align-self: center; margin-left: 10px"> Search </button>
                </form>
            </div>

            <div class="row justify-content-center">

                @foreach($houses as $house)
                
                <div class="card house-card d-flex">
                    <div class="card-block d-flex" style=" flex-direction: column; text-align: center">
                        <label> Titulo: {{ $house->title }} </label>
                        <label> Price: {{ $house->value }} </label>
                        <label> ID: {{ $house->id }} </label>
                    </div>
                    <div class="card-block d-flex" style="justify-content: center">
                        <a href="{{ route('house.show', $house->id)}}" class="btn btn-primary" style="margin-top: 20px;margin-bottom: 20px"> Show </a>
                    </div>
                </div>

                @endforeach
            </div>
        </div>
    </div>
    <div class="d-flex" style="margin-top: 20px; justify-content: center;">
        <?php echo $houses->render(); ?>
    </div>
@endsection

resources/views/house/xml.blade.php
@extends('layouts.app')
    
@section('content')    
	<div class="container">
	    <div class="row justify-content-center">
		    <form action="consumeXML" method="POST" enctype="multipart/form-data">
		    	{{ csrf_field() }}
		    	<div class="form-group d-flex" style="flex-direction: column; justify-content: center; margin-top: 20px">
			        <input id="xmlfile" class="form-control" type="file" name="xmlFile" accept="text/xml">
			        <button type="submit" class="btn btn-primary" style="max-width: 150px; align-self: center; margin-top: 20px" name="xml-btn"> Consume XML </button>
			    </div>
		    </form>
		</div>
	</div>
@endsection